### ISSUE TITLE
Add support for datacite.xml and a corresponding citation string

### ISSUE THREAD

**Issue by ptsefton** [Language-Research-Technology/ro-crate-js#10]
Based on this legacy code -- add a method to this library produce a datacite XML file "@id": "datacite.xml" for a crate and add an option to do this via the ro-crate-html-js commandline and link to it via a citeas.

This code should more or less still work.

https://github.com/UTS-eResearch/CalcyteJS/blob/d9b1bb952c845e36def807564c784ba6735f8c8a/lib/datacite.js

The name property of the datacite.xml file should be a formatted XML citation - see https://datacite.org/cite-your-data.html

**Comment by ptsefton** [comment]
@alvinsw we should look at this soon...

**Comment by moisbo** [comment]
No need for XML creation and just add a text citation to "cite-as"
