### ISSUE TITLE
Bug: When adding a reference to an existing entity in 'replace' mode it removes properties from the linked entity

### ISSUE THREAD

**Issue by ptsefton** [Language-Research-Technology/ro-crate-js#12]
See branch: removing-existing-entities. Added a test: "Does not kill existing entities" in `tests/rocrate.new.spec.js`

When you add a property value with a reference to another entity, then props go missing

**Comment by ptsefton** [comment]
(Only the @type prop remains...)

**Comment by alvinsw** [comment]
Fixed in v.3.3.2
