### ISSUE TITLE
no type for some items when getGraph()

### ISSUE THREAD

**Issue by moisbo** [Language-Research-Technology/ro-crate-js#2]
if you add a reference to an external URI like "conformsTo": {"@id", "http://purl.archive.org/etc"} then when you getGraph() you get entries like {"@id", "http://purl.archive.org/etc"}  --- this should not happen

If it had other props then it needs to be treated as a separate thing (and if no type then it should be forced to be Thing

See commit https://github.com/Arkisto-Platform/ro-crate-js/commit/083c1d2e9899fadd22c5d5448f7ccbbcea75e99b

**Comment by alvinsw** [comment]
I have fixed it in the branch [release/v3.2.0](https://github.com/Arkisto-Platform/ro-crate-js/tree/release/v3.2.0)
