### ISSUE TITLE
Make the documentation for addContext clearer

### ISSUE THREAD

**Issue by marcolarosa** [Language-Research-Technology/ro-crate-js#7]
https://github.com/Arkisto-Platform/ro-crate-js/blob/9d767472080ec745323ee136d40f55aa6b0c5d0d/lib/rocrate.js#L899-L902

This was confusing to me. I initially interpreted it to mean "Add my context in, replacing the default context" rather than "add something to the default context".

**Comment by alvinsw** [comment]
Yes it is still work in progress. Basically the method adds the object (whatever it is) passed as the `context` parameter to the array of '@context' property.
Do you have a suggestion on how to word that properly?
Also do we need a method to set the context, ie replacing the whole exisiting context?

**Comment by marcolarosa** [comment]
```
 /** 
    * Add context 
    * @param {String|Object} context - Add an entry to the context. This method will insert the string or object provided directly into the context array. It does not check for duplicates or overlapping content.
    */ 
```
