### ISSUE TITLE
Nice to have: addEntity automatically handle complex objects

### ISSUE THREAD

**Issue by marcolarosa** [Language-Research-Technology/ro-crate-js#8]
If I do:

```
const location = {
  '@id': '#Erakor village',
  '@type': 'Place',
  name: 'Erakor village',
  geo: {
    '@id': '#geo_Erakor village',
    '@type': 'GeoCoordinates',
    name: 'Geographical coverage for Erakor village',
    geojson: '{"type":"Feature","properties":{"name":"Erakor village"},"geometry":{"type":"Polygon","coordinates":[[[168.159,-17.585],[168.159,-17.83],[168.594,-17.83],[168.594,-17.585],[168.159,-17.585]]]}}'
  }
}
crate.addEntity(location)
```

I get:

```
 {
      "@id": "#Erakor village",
      "@type": "Place",
      "name": "Erakor village",
      "geo": {
          "@id": "#geo_Erakor village"
       }
}
```

But there is no entity for `{ "@id": "#geo_Erakor village" }`. That is, the entity that the `geo` property points to in the location object has been lost.

At the very least you will need this if pulling data from [Describo Data Packs](https://describo.github.io/data-packs/)

See: https://describo.github.io/data-packs/global.html#CountryEntryDataFormat
and 
https://describo.github.io/data-packs/global.html#LanguageEntryDataFormat-Austlang

**Comment by alvinsw** [comment]
The `addEntity` method has the third parameter `recurse` that must be set to true, eg: `crate.addEntity(location, false, true)`. What I am unsure is if the default should be true. 
Also it might be better to change the method signature into  `addEntity(data: any, opt: { replace: boolean, recurse: boolean }) `.

What do you think?

**Comment by marcolarosa** [comment]
I have no preference for whether the default is true or false. I think the solution here involves focusing on making the docs more easily accessible because I missed that capability whilst looking at the code as an outsider (remember: I'm not familiar with the codebase).

**Comment by alvinsw** [comment]
Link to the [API documentation](https://arkisto-platform.github.io/ro-crate-js/) is now displayed prominently in the readme.
