### ISSUE TITLE
I don't think this works with references to html pages

### ISSUE THREAD

**Issue by marcolarosa** [Language-Research-Technology/ro-crate-js#9]
https://github.com/Arkisto-Platform/ro-crate-js/blob/9d767472080ec745323ee136d40f55aa6b0c5d0d/lib/rocrate.js#L919

If I have a context like:
```
"@context": [
        "https://w3id.org/ro/crate/1.1/context",
        {
            "@vocab": "http://schema.org/"
        },
        "http://purl.archive.org/language-data-commons/context.json",
        "https://language-archives.services/metadata-definitions/#media"
    ],
```

And you follow the link https://language-archives.services/metadata-definitions/#media (assume the definitions have actually been written) then I thought this met the requirements.

But the ro-crate `#resolveTerm` function seems to have been written to assume that a context entry resolves to a JSON file where the property can be resolved. (With the property then linking off to the description)

Is that correct? This is an issue in the validator in that it is complaining that the context is not correct when I thought it was.

**Comment by alvinsw** [comment]
I think context references using a URL as in your example needs to resolve to a valid jsonld. So yes the "https://language-archives.services/metadata-definitions/#media" must resolve to a proper jsonld. 
It is a different case for the term and it's IRI which does not have to resolve to jsonld. For example:
```
"@context": [
  "https://language-archives.services/metadata-definitions/#media", <-- this must be jsonld
  {
    media: "https://language-archives.services/metadata-definitions/#media" <-- this can be anything
  }
]
```

I will wait for Peter to confirm this.
Reference here: https://www.w3.org/TR/json-ld11/#the-context

**Comment by marcolarosa** [comment]
Closing this - i looked back at some of my code and realised I was doing it incorrectly. My bad.
